config/routes.rb
Lingapps::Application.routes.draw do

	root :to => 'home#index'

  get "sessions/new"

    match '/users/query', :to => 'users#query'
	match '/translations/create', :to => 'translations#create'
	match '/projects/query', :to => 'projects#query'
	match '/projects/createjson', :to => 'projects#createjson'

    resources :users
	resources :sessions, :only => [:new, :create, :destroy]
	resources :projects  
	resources :languages
	resources :expressions
	resources :translations
	resources :word_lists

	match '/newproj', :to => 'projects#new'

	match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/dashboard', :to => 'pages#dashboard'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/myprojects', :to => 'pages#myprojects'
  match '/insitu', :to => 'pages#insitu'
  match '/mobileapps', :to => 'pages#mobileapps'

end

app/views/pages/about.html.erb
<h1>About</h1>
	<p>LingApps is an effort to develop mobile apps for linguistics.</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	<ul>  
		<li>
			Project coordinator: <a href="http://faculty.washington.edu/farrar">Scott Farrar</a>
		</li>
		<li>
			App coordinator: <a href="http://students.washington.edu/kellypet/">Kelly Peterson</a>
		</li>

	</ul>
</p>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

<p>LingApps contains various apps:</p>

<ul>
	<li><b>In Situ:</b> An app for managing and using word lists.
	</li>  
<%= button_to "New Project", {:controller => 'projects', :action => 'new'}, :method => :get  %>
</ul>

app/views/pages/insitu.html.erb
<h1>In Situ</h1>

<p>
<b>In Situ</b> is a mobile app to manage and create word lists.
</p> 

<h3>Download:</h3>

<ul>
	<li>
		In Situ Android app
	</li>
</ul>

app/views/pages/mobileapps.html.erb
<h1>Mobile Apps</h1>



<ul>
	<li>
		<%= link_to "In Situ", insitu_path %>
	</li>
</ul>

app/views/pages/myprojects.html.erb
<h1>My Projects</h1>

<ul>
<% current_user.projects.each do |project|  %>
	<li>
		<%= link_to project.name, project %>
	</li>
<% end %>
</ul>

<%= button_to "New Project", {:controller => 'projects', :action => 'new'}, :method => :get  %>