config/routes.rb
Lingapps::Application.routes.draw do

	root :to => 'home#index'

  get "sessions/new"

    match '/users/query', :to => 'users#query'
	match '/translations/create', :to => 'translations#create'
	match '/projects/query', :to => 'projects#query'
	match '/projects/createjson', :to => 'projects#createjson'

    resources :users
	resources :sessions, :only => [:new, :create, :destroy]
	resources :projects  
	resources :languages
	resources :expressions
	resources :translations
	resources :word_lists

	match '/newproj', :to => 'projects#new'

	match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/dashboard', :to => 'pages#dashboard'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/myprojects', :to => 'pages#myprojects'
  match '/insitu', :to => 'pages#insitu'
  match '/mobileapps', :to => 'pages#mobileapps'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
   </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= link_to logo, root_path  %>
    <nav class="round">
        <ul>
            <li><%= link_to "Home", root_path %></li>
            <% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <% end %>
						<li><%= link_to "Mobile", mobileapps_path  %></li>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <% if signed_in? %>
					
            <li><%= link_to "MyProjects", myprojects_path %></li>
	
            <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
            <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
    </nav>

		<%if ! signed_in? %>
			<navc class="button">
			<input type="image" src="images/sign_up_yellow_small.png" value="submit" alt="submit" onClick="parent.location='<%= signup_path  %>'"/>
			</navc>
		<% end %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets'%>
<%= javascript_include_tag :defaults %>
  </head>
<body>
  <div class="container">
  <%= render 'layouts/header'%>
    <section class="round">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    
    <%= yield %>
    </section>
  <%= render 'layouts/footer'%>
<%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>